language: node_js
node_js: 
  - 'node'
install: npm install
services:
  - postgresql
addons:
  postgresql: "9.6"

cache:
  directories:
    - "node_modules"
env:
  global:
    - DB_ENV=testing
before_script:
  - psql -c 'create database backend_test;' -U postgres
  - psql -c "CREATE USER root WITH PASSWORD 'password';" -U postgres
  - psql -c "ALTER ROLE root CONNECTION LIMIT -1"
  - npx knex migrate:down --env=testing
  - npx knex migrate:rollback --env=testing
  - npx knex migrate:latest --env=testing
  - npx knex seed:run --env=testing
  - npm install coveralls
script:
  - npm test
after_script:
  - npm install
  - npm knex migrate:down --env=testing
  - npx knex migrate:rollback --env=testing
  - npx knex migrate:latest --env=testing
  - npx knex seed:run --env=testing
  - jest --forceExit --coverage  --coverageReporters=text-lcov | coveralls 
notifications:
  email: false

