language: node_js
node_js: 
  - '8'
services:
  - postgresql
cache:
  directories:
    - "node_modules"
env:
  global:
    - DB_ENV=testing
   
before_script:
  - psql -c 'create database backend_test;' -U postgres
  - psql -c "CREATE USER root WITH PASSWORD 'password';" -U postgres
  - npx knex migrate:down --env=testing
  - npx knex migrate:rollback --env=testing
  - npx knex migrate:latest --env=testing
  - npx knex seed:run --env=testing
  - npm install coveralls
script:
  - npm test
  - sudo /etc/init.d/postgresql stop 
after_script:
  - jest --forceExit --coverage  --coverageReporters=text-lcov | coveralls 
notifications:
  email: false
